database:
    connection:
        driver:     pdo_mysql
        host:       database
        dbname:     eole
        user:       root
        password:   root
        charset:    utf8

websocket:
    server:
        bind:       0.0.0.0
        port:       8482

push:
    enabled:        true
    server:
        bind:       0.0.0.0
        host:       websocket-server
        port:       5555
